{
	"version": 1624554910,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/heroe-sheet0.png",
		"images/heroe-sheet1.png",
		"images/gemelo2-sheet0.png",
		"images/gemelo2-sheet1.png",
		"images/gemelo2-sheet2.png",
		"images/sprite7-sheet0.png",
		"images/play-sheet0.png",
		"images/iravideo-sheet0.png",
		"images/exit-sheet0.png",
		"images/fondo-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/creditos-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/gameover-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/barravida-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/musica.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"video cultura física.mp4"
	]
}